sudo: required
services:
  - docker

before_install:
  - docker build -t ebjacobs98/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ebjacobs98/react-test npm test

after_success:
  - docker build -t ebjacobs98/multi-client ./client
  - docker build -t ebjacobs98/multi-nginx ./nginx
  - docker build -t ebjacobs98/multi-server ./server
  - docker build -t ebjacobs98/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push ebjacobs98/multi-client 
  - docker push ebjacobs98/multi-nginx 
  - docker push ebjacobs98/multi-server 
  - docker push ebjacobs98/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-142259036050"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY